### Extract text with PDFminer

In [1596]:
# !pip install pdfminer.six
from io import StringIO

from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.pdfpage import PDFPage
from pdfminer.pdfparser import PDFParser

output_string = StringIO()

with open(r'C:\Users\rc_sh\OneDrive\Escritorio\AI\Machine_Learning\Walmart\2020\12_Diciembre\28-12-2020.pdf', 'rb') as in_file:
# with open(r'C:\Users\rc_sh\OneDrive\Escritorio\AI\Machine_Learning\Walmart\2020\Receipts_2020.pdf', 'rb') as in_file:
    parser = PDFParser(in_file)
    doc = PDFDocument(parser)
    rsrcmgr = PDFResourceManager()
    device = TextConverter(rsrcmgr, output_string, laparams=LAParams())
    interpreter = PDFPageInterpreter(rsrcmgr, device)
    for page in PDFPage.create_pages(doc):
        interpreter.process_page(page)

print(output_string.getvalue())

ADMIN. DE SUPERMERCADOS HIPER
LIMITADA
76.134.941-4
GRANDES ESTABLECIMIENTOS-VENTA DE
ALIM.

BOLETA ELECTRÓNICA Nº :

1680354484

LOCAL:

0682

CAJA:

022

FECHA EMISION:

28-12-2020

TRAN. Nº:

0145

CAJERO:

493

HORA:

18:29

CANT.

PRECIO UNIT.

DESC. ARTICULO

VALOR

3.900

2.090

3.590

1.490

3.490

1.390

2.190

2.990

3.390

1.150

1.090

5.650

5.990

564

1.280

2.290

1.473

590

650

650

850

950

1.390

610

1.230

1.650

1.490

- 900

44.678
0
8.489
53.167

CODIGO: 07804144000468
2.0X 1.950 HUEVO GRANDE
CODIGO: 08410376017694
1.0X 2.090 DIET NATURE
CODIGO: 07804613390632
1.0X 3.590 QUESO CHANCO
CODIGO: 07801930014555
1.0X 1.490 PECHPAVOPF
CODIGO: 07809611715081
1.0X 3.490 PECHUGA DESH
CODIGO: 07804627330013
1.0X 1.390 ACEITUNA REL
CODIGO: 07804115001777
1.0X 2.190 AZ-MOL PH PA
CODIGO: 00614143030901
1.0X 2.990 ARANDANO
CODIGO: 07804068002043
1.0X 3.390 CIRUELAS MED
CODIGO: 07801220001203
1.0X 1.150 ENSALADA MIX
CODIGO: 07801365000284
1.0X 1.090 CHAMPINON BA
CODIGO: 00722776200629
1.0X 5.650 SPLENDA GRAN
CODIGO: 07613036150521
1.0X 5.990 BUEN DIA 1.1
CODIGO: 02030100000004
0.355X 1.589 MANZ VERDE
CODIGO: 07801420130130
1.0X 1.280 ARROZ INTEGR
CODIGO: 07804644940301
1.0X 2.290 NARANJA 1.5
CODIGO: 02006100000009
0.74X 1.991 NECTARIN
CODIGO: 07804087000051
1.0X 590 CILANTRO BOL
CODIGO: 07804628680339
1.0X 650 PIMIENTO VER
CODIGO: 07802341000366
1.0X 650 CEBOLLIN
CODIGO: 07804613170524
1.0X 850 ZANAHORIAS B
CODIGO: 07804613170098
1.0X 950 HOJAS ESPINA
CODIGO: 07804622260063
1.0X 1.390 ZAPALLO CAMO
CODIGO: 07804602170184
1.0X 610 ZAPALLO ITAL
CODIGO: 07804930000306
1.0X 1.230 LIMP CREMA
CODIGO: 07801320220061
1.0X 1.650 ACEITE MARA.
CODIGO: 07802636002921
1.0X 1.490 MRRQTA ATM

@@Descuento Global   ($)

TOTAL AFECTO
TOTAL EXENTO
TOTAL IVA (19.0%)
TOTAL

$
$
$
$

TBK CREDITO                 $     53.167
VUELTO                      $          0

TOTAL ARTICULOS = 28

Timbre Electrónico SII
 Res. 85 del 2011. - Verifique documento: http://www.lider.cl

0145 0682/022/493   28.12.20 18:29 AC-00
ATENDIDO POR : cajero  exrerno

Revisa tu boleta en: WWW.LIDER.CL

#############  L I D E R  #############
##### PRECIOS BAJOS TODOS LOS DIAS #####

### Extract fields with Regular Expressions

Regex1: CODIGO:\s(.+?)\n(.+?)[Xx]\s(.+?)\s(.*?)\n

Regex2: BOLETA ELECTRÓNICA Nº :\n\n(.+?)\n\nLOCAL:\n\n(.+?)\n\nCAJA:\n\n(.+?)\n\nFECHA EMISION:\n\n(.+?)\n\nTRAN. Nº:\n\n(.+?)\n\nCAJERO:\n\n(.+?)\n\nHORA:\n\n(.+?)\n\n

Regex3: TOTAL ARTICULOS =(.+?)\n

Regex4: ATENDIDO POR :\s(.+?)\n

In [1597]:
import re
# Extract: Code, Quantity, Unit Price, Description
raw_data1 = re.findall('CODIGO:\s(.+?)\n(.+?)[Xx]\s(.+?)\s(.*?)\n' ,  output_string.getvalue(), re.M)
# raw_data1

In [1598]:
import pandas as pd
df1 = pd.DataFrame(raw_data1, columns =['codigo', 'cantidad', 'precio_unitario', 'descripcion'])
df1

            codigo cantidad precio_unitario   descripcion
0   07804144000468      2.0           1.950  HUEVO GRANDE
1   08410376017694      1.0           2.090   DIET NATURE
2   07804613390632      1.0           3.590  QUESO CHANCO
3   07801930014555      1.0           1.490    PECHPAVOPF
4   07809611715081      1.0           3.490  PECHUGA DESH
5   07804627330013      1.0           1.390  ACEITUNA REL
6   07804115001777      1.0           2.190  AZ-MOL PH PA
7   00614143030901      1.0           2.990      ARANDANO
8   07804068002043      1.0           3.390  CIRUELAS MED
9   07801220001203      1.0           1.150  ENSALADA MIX
10  07801365000284      1.0           1.090  CHAMPINON BA
11  00722776200629      1.0           5.650  SPLENDA GRAN
12  07613036150521      1.0           5.990  BUEN DIA 1.1
13  02030100000004    0.355           1.589    MANZ VERDE
14  07801420130130      1.0           1.280  ARROZ INTEGR
15  07804644940301      1.0           2.290   NARANJA 1.5
16  02006100000009     0.74           1.991      NECTARIN
17  07804087000051      1.0             590  CILANTRO BOL
18  07804628680339      1.0             650  PIMIENTO VER
19  07802341000366      1.0             650      CEBOLLIN
20  07804613170524      1.0             850  ZANAHORIAS B
21  07804613170098      1.0             950  HOJAS ESPINA
22  07804622260063      1.0           1.390  ZAPALLO CAMO
23  07804602170184      1.0             610  ZAPALLO ITAL
24  07804930000306      1.0           1.230    LIMP CREMA
25  07801320220061      1.0           1.650  ACEITE MARA.
26  07802636002921      1.0           1.490    MRRQTA ATM

In [1599]:
raw_data2 = re.findall('BOLETA ELECTRÓNICA Nº :\n\n(.+?)\n\nLOCAL:\n\n(.+?)\n\nCAJA:\n\n(.+?)\n\nFECHA EMISION:\n\n(.+?)\n\nTRAN. Nº:\n\n(.+?)\n\nCAJERO:\n\n(.+?)\n\nHORA:\n\n(.+?)\n\n' ,  output_string.getvalue(), re.M)
# raw_data2

In [1600]:
df2 = pd.DataFrame(raw_data2, columns =['boleta_electronica', 'local', 'caja', 'fecha_emision', 'trans_n', 'cajero', 'hora']
)
df2

  boleta_electronica local caja fecha_emision trans_n cajero   hora
0         1680354484  0682  022    28-12-2020    0145    493  18:29

In [1601]:
raw_data3 = re.findall('TOTAL ARTICULOS =(.+?)\n' ,  output_string.getvalue(), re.M)
# raw_data3

In [1602]:
df3 = pd.DataFrame(raw_data3, columns =['total_articulos'])
df3

  total_articulos
0              28

In [1603]:
raw_data4 = re.findall('ATENDIDO POR :\s(.+?)\n' ,  output_string.getvalue(), re.M)
# raw_data4

In [1604]:
df4 = pd.DataFrame(raw_data4, columns =['atendido_por'])
df4

      atendido_por
0  cajero  exrerno

### Save the data to a csv

In [1605]:
 df1.to_csv(r'C:\Users\rc_sh\OneDrive\Escritorio\AI\Machine_Learning\reading_receipts\Data from individual receips\data1.csv', index = False)
# df2.to_csv(r'C:\Users\rc_sh\OneDrive\Escritorio\AI\Machine_Learning\reading_receipts\Data from individual receips\data2.csv', index = False)
# df3.to_csv(r'C:\Users\rc_sh\OneDrive\Escritorio\AI\Machine_Learning\reading_receipts\Data from individual receips\data3.csv', index = False)
# df4.to_csv(r'C:\Users\rc_sh\OneDrive\Escritorio\AI\Machine_Learning\reading_receipts\Data from individual receips\data4.csv', index = False)